version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/main
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
